#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 32
#define LV_COLOR_SCREEN_TRANSP 0
#define LV_COLOR_16_SWAP 0

#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (64U * 1024U)
#define LV_MEM_ADR 0

#define LV_HOR_RES_MAX 800
#define LV_VER_RES_MAX 480
#define LV_DPI_DEF 130

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

#define LV_USE_ASSERT_NULL 1
#define LV_USE_ASSERT_MALLOC 1
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_USE_PERF_MONITOR 0
#define LV_USE_MEM_MONITOR 0
#define LV_USE_REFR_DEBUG 0

#define LV_USE_LABEL 1
#define LV_LABEL_TEXT_SELECTION 0
#define LV_LABEL_LONG_TXT_HINT 1

#define LV_USE_BTN 1
#define LV_USE_CANVAS 0
#define LV_USE_IMG 0
#define LV_USE_LINE 0
#define LV_USE_ARC 0
#define LV_USE_SLIDER 0
#define LV_USE_SWITCH 0
#define LV_USE_CHECKBOX 0
#define LV_USE_DROPDOWN 0
#define LV_USE_ROLLER 0
#define LV_USE_TEXTAREA 0
#define LV_USE_TABLE 0
#define LV_USE_BAR 0
#define LV_USE_SPINBOX 0
#define LV_USE_SPINNER 0
#define LV_USE_KEYBOARD 0
#define LV_USE_MSGBOX 0
#define LV_USE_WINDOW 0
#define LV_USE_TILEVIEW 0
#define LV_USE_TABVIEW 0
#define LV_USE_LIST 0
#define LV_USE_MENU 0
#define LV_USE_CALENDAR 0
#define LV_USE_CALENDAR_HEADER_ARROW 0
#define LV_USE_CALENDAR_HEADER_DROPDOWN 0

#define LV_USE_FLEX 1
#define LV_USE_GRID 1

#define LV_USE_THEME_DEFAULT 1
#define LV_THEME_DEFAULT_DARK 1
#define LV_THEME_DEFAULT_GROW 1
#define LV_THEME_DEFAULT_TRANSITION_TIME 80
#define LV_THEME_DEFAULT_ROUND 0

#define LV_FONT_DEFAULT &lv_font_montserrat_14
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_28 1

#define LV_BUILD_EXAMPLES 0
#define LV_BUILD_TEST 0

#define LV_USE_FS_STDIO 0
#define LV_USE_PERF_MONITOR 0

#endif